#!/bin/bash
# Small script for rolling out the helm chart
DEFAULT_HELM_CHART=collectionchart
DEFAULT_HELM_DIR=./helm-dir
DEFAULT_NAMESPACE="iperf-collect"


# Check for the Helm Chart
if [[ "${HELM_CHART}" == "" ]]; then
    echo "Using default helm chart. ${DEFAULT_HELM_CHART}"
    HELM_CHART=${DEFAULT_HELM_CHART}
fi

if [[ "${HELM_DIR}" == "" ]]; then
    echo "Using default helm directory. ${DEFAULT_HELM_DIR}"
    HELM_DIR=${DEFAULT_HELM_DIR}
fi

# Roll out the Helm Chart
echo "Attempting to remove any existing deployments. IGNORE any uninstall errors."
helm uninstall ${HELM_CHART} | true

echo "Attempting to deploy"
helm install ${HELM_CHART} ${HELM_DIR} -n ${DEFAULT_NAMESPACE} --values ${HELM_DIR}/values.yaml --create-namespace

echo "Tool deployed successfully"
