#!/bin/bash
# Small script for rolling out the helm chart
DEFAULT_HELM_CHART=collectionchart
DEFAULT_HELM_DIR=./helm-dir
DEFAULT_NAMESPACE="iperf-collect"  

# Check for the Helm Chart
if [[ "${HELM_CHART}" == "" ]]; then
    echo "Using default helm chart. ${DEFAULT_HELM_CHART}"
    HELM_CHART=${DEFAULT_HELM_CHART}
fi

helm uninstall ${HELM_CHART} -n ${DEFAULT_NAMESPACE} 
echo "Tool successfully removed"
